{{- if .Values.backfillredis.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "rekor.backfillredis.fullname" . }}
{{ include "rekor.namespace" . | indent 2 }}
  labels:
    {{- include "rekor.labels" . | nindent 4 }}
{{- if .Values.backfillredis.annotations }}
  annotations:
{{ toYaml .Values.backfillredis.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.backfillredis.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.backfillredis.ttlSecondsAfterFinished }}
{{- end }}
  template:
    spec:
      serviceAccountName: {{ template "rekor.serviceAccountName.server" . }}
      restartPolicy: Never
      containers:
        - name: {{ template "rekor.backfillredis.fullname" . }}
          image: "{{ template "rekor.image" .Values.backfillredis.image }}"
          imagePullPolicy: "{{ .Values.backfillredis.image.pullPolicy }}"
          args: [
            "--hostname={{ template "redis.hostname" . }}",
            "--port={{ .Values.redis.port }}",
            "--rekor-address={{ .Values.backfillredis.rekorAddress }}",
            "--start={{ .Values.backfillredis.startIndex }}",
            "--end={{ .Values.backfillredis.endIndex }}",
          ]
    {{- if .Values.backfillredis.securityContext }}
      securityContext:
{{ toYaml .Values.backfillredis.securityContext | indent 8 }}
    {{- end }}
{{- end }}
