{{- if .Values.createtree.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "ctlog.createtree.fullname" . }}
{{ include "ctlog.namespace" . | indent 2 }}
  labels:
    {{- include "ctlog.labels" . | nindent 4 }}
{{- if .Values.createtree.annotations }}
  annotations:
{{ toYaml .Values.createtree.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.createtree.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.createtree.ttlSecondsAfterFinished }}
{{- end }}
  template:
    spec:
      serviceAccountName: {{ template "ctlog.serviceAccountName.createtree" . }}
      restartPolicy: Never
      automountServiceAccountToken: {{ .Values.createtree.serviceAccount.mountToken }}
      containers:
        - name: {{ template "ctlog.createtree.fullname" . }}
          image: "{{ template "ctlog.image" .Values.createtree.image }}"
          imagePullPolicy: "{{ .Values.createtree.image.pullPolicy }}"
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          args: [
            "--namespace=$(NAMESPACE)",
            "--configmap={{ template "ctlog.config" . }}",
            "--display_name={{ .Values.createtree.displayName }}",
            "--admin_server={{ .Values.trillian.logServer.name }}.{{ .Values.trillian.namespace }}:{{ .Values.trillian.logServer.portRPC}}"
          ]
    {{- if .Values.createtree.resources }}
          resources:
{{ toYaml .Values.createtree.resources | indent 12 }}
    {{- end }}
    {{- if .Values.createtree.securityContext }}
      securityContext:
{{ toYaml .Values.createtree.securityContext | indent 8 }}
    {{- end }}
{{- end }}
