{{- if and .Values.createtree.enabled .Values.createtree.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ctlog.serviceAccountName.createtree" . }}
{{ include "ctlog.namespace" . | indent 2 }}
  labels:
    {{- include "ctlog.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.createtree.serviceAccount.annotations | indent 4 }}
{{- end }}
