apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ctlog.serviceAccountName.createctconfig" . }}
{{ include "common.names.namespace" . | indent 2 }}
  labels:
    {{- include "common.labels.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.createctconfig.serviceAccount.annotations | indent 4 }}