apiVersion: v2
name: tuf
description: A framework for securing software update systems - the scaffolding implementation
type: application
version: 0.1.8
appVersion: "0.6.10"

home: https://sigstore.dev/
sources:
  - https://github.com/sigstore/scaffolding

maintainers:
- name: The Sigstore Authors
  url: https://sigstore.dev/

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: scaffolding-tuf
      image: ghcr.io/sigstore/scaffolding/server:v0.6.10@sha256:5e0c4500fb8c93a2f93787af5a4e9620d4905ef99d587ec7ce1119d904de58c9
