apiVersion: v2
name: tuf
description: A framework for securing software update systems - the scaffolding implementation
type: application
version: 0.1.11
appVersion: "0.6.16"

home: https://sigstore.dev/
sources:
  - https://github.com/sigstore/scaffolding

maintainers:
- name: The Sigstore Authors
  url: https://sigstore.dev/

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: scaffolding-tuf
      image: ghcr.io/sigstore/scaffolding/server:v0.6.16@sha256:66084c466e3a0a53e83bdc72561ce79dc8f2783a6dd34144a907054e50737eb7
