apiVersion: v2
name: tuf
description: A framework for securing software update systems - the scaffolding implementation
type: application
version: 0.1.29
appVersion: 0.7.31

home: https://sigstore.dev/
sources:
  - https://github.com/sigstore/scaffolding

maintainers:
- name: The Sigstore Authors
  url: https://sigstore.dev/

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: scaffolding-tuf
      image: ghcr.io/sigstore/scaffolding/server:v0.7.31@sha256:ae8eb69c7b7065456370c7025ff781487704352d73231b08d16b525b0cb16b54
