apiVersion: v2
name: tuf
description: A framework for securing software update systems - the scaffolding implementation
type: application
version: 0.1.21
appVersion: 0.7.15

home: https://sigstore.dev/
sources:
  - https://github.com/sigstore/scaffolding

maintainers:
- name: The Sigstore Authors
  url: https://sigstore.dev/

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: scaffolding-tuf
      image: ghcr.io/sigstore/scaffolding/server:v0.7.15@sha256:982c6173b6f2f976fd9f58eb543ca9ec5f0d1b7c1a6f7bb0c4b96cff1618c62e
