apiVersion: v2
name: ctlog
description: Certificate Log

type: application

version: 0.2.52
appVersion: 0.6.17

keywords:
  - security
  - pki

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: ct_server
      image: ghcr.io/sigstore/scaffolding/ct_server:v0.6.17@sha256:e16f0a2be43a317a4c392cca24eec8c8fef06b0e836bc3545979ac0335fcf6f5
    - name: createctconfig
      image: ghcr.io/sigstore/scaffolding/createctconfig:v0.6.17@sha256:a891233c7f54a11025a4cac6119ba4aeea4f643c2012ff30e921aeca8a32d6db
    - name: createtree
      image: ghcr.io/sigstore/scaffolding/createtree:v0.6.17@sha256:eb1a94738f34964c7456d18d30b8a45a654af89bb5371f69b2403df373be0826
    - name: curlimages/curl
      image: docker.io/curlimages/curl:8.5.0@sha256:4bfa3e2c0164fb103fb9bfd4dc956facce32b6c5d47cc09fcec883ce9535d5ac
