apiVersion: v2
name: ctlog
description: Certificate Log

type: application

version: 0.2.21
appVersion: 0.3.0

keywords:
  - security
  - pki

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: ct_server
      image: ghcr.io/sigstore/scaffolding/ct_server@sha256:7c791d3b7c15e817807f07d4cdb00406529a114702ad448ee857e1d0fc5fb5a9
    - name: createctconfig
      image: ghcr.io/sigstore/scaffolding/createctconfig@sha256:2795b42d3b42cdb9eaf3825e0bca742963208a51e30d5a7173f8a68ac6d47732
    - name: createtree
      image: ghcr.io/sigstore/scaffolding/createtree@sha256:d5776d8a43632291e1c5a22a9266608db0daa0a11663445d701e327f2205974c
