apiVersion: v2
name: rekor-tiles
description: Part of the sigstore project, Rekor v2 (Rekor on tiles) is a signature transparency log
type: application
version: 1.1.2
appVersion: "2.2.1"
keywords:
  - security
  - transparency logs
home: https://sigstore.dev/
sources:
  - https://github.com/sigstore/rekor-tiles
maintainers:
  - name: The Sigstore Authors
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: rekor-tiles-gcp
      image: ghcr.io/sigstore/rekor-tiles/gcp:v2.2.1@sha256:17f6584cc8f531083a56d3ff2dd4e03b00c604a6b6f6bc62a5e29c7baea46895
    - name: rekor-tiles-posix
      image: ghcr.io/sigstore/rekor-tiles/posix:v2.2.1@sha256:627422bf9da146d1d9ff4e1c1e8301a1780ab6ad9b32bccff51ecd9f8c820e41
