apiVersion: v2
name: updatetree
description: Update the status of an existing Trillian tree

type: application

version: 0.0.22
appVersion: 0.7.31


keywords:
  - security
  - trillian
  - updatetree

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: updatetree
      image: ghcr.io/sigstore/scaffolding/updatetree:v0.7.31@sha256:66f47d58ec4f47e322345cfc783b3d8816624961feec9bc0063d35b8267645fe
