apiVersion: v2
name: tsa
description: |
  Timestamp Authority issuing RFC3161 signed timestamps.

type: application

version: 2.0.0
appVersion: 2.0.1

keywords:
  - security
  - timestamp

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: tsa
      # crane digest ghcr.io/sigstore/timestamp-server:v2.0.1
      image: ghcr.io/sigstore/timestamp-server:v2.0.1@sha256:0a619f2aa7bb7516e6c56f1f34bec1f2d5d4681c53c7a456898b84f90afc89a1
