apiVersion: v2
name: tsa
description: |
  Timestamp Authority issuing RFC3161 signed timestamps.

type: application

version: 0.1.0
appVersion: 0.1.3

keywords:
  - security
  - timestamp

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: tsa
      # crane digest ghcr.io/sigstore/timestamp-server:v0.1.3
      image: ghcr.io/sigstore/timestamp-server@sha256:09ecc219c4b279d6b5652a80d4d2201f55178e2cb233462da085ef3799acb823
