namespace:
  create: false
  name: tsa-system

server:
  replicaCount: 1
  name: server
  svcPort: 80
  grpcSvcPort: 5554
  secret: tsa-server-secret
  logging:
    production: false
  env:
    GOOGLE_APPLICATION_CREDENTIALS: /etc/tsa-config/cloud_credentials
  image:
    registry: ghcr.io
    repository: sigstore/timestamp-server
    pullPolicy: IfNotPresent
    # crane digest ghcr.io/sigstore/timestamp-server:v1.2.2
    # -- v1.2.2
    version: sha256:9f012408a0b2a91a0f017df419b732556a0bdd7482973dc3b87fe979e41ccc9a
  args:
    port: 5555
    # Valid values: tink, kms, file
    signer: tink
    # PEM encoded cert chain here. Order from active intermedate first to root last
    cert_chain: chain
    tink_enc_keyset: keyset
    tink_key_resource: resource
    tink_hcvault_token: token
    kms_key_resource: resource
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: true
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 5555
      - name: metrics
        port: 2112
        protocol: TCP
        targetPort: 2112
  ingress:
    http:
      enabled: true
      className: "nginx"
      annotations: {}
      hosts:
      - path: /
        host: "timestamp.localhost"
      tls: []
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
  tolerations: []
  nodeSelector: {}
  affinity: {}

# Force namespace of namespaced resources
forceNamespace: ""
