namespace:
  create: false
  name: tsa-system

server:
  replicaCount: 1
  name: server
  svcPort: 80
  secret: tsa-server-secret
  logging:
    production: false
  env:
    # Credentials file read by kms/tink if set. Unset by default
    GOOGLE_APPLICATION_CREDENTIALS: ""
  image:
    registry: ghcr.io
    repository: sigstore/timestamp-server
    pullPolicy: IfNotPresent
    # crane digest ghcr.io/sigstore/timestamp-server:v2.0.3
    version: v2.0.3@sha256:24f74ba81e5b9523f6b6735cba84bfd0963b6a0be68e1d73ef86db7d38f18fda
  args:
    port: 5555
    # Valid values: tink, kms, file
    signer: tink
    # PEM encoded cert chain here. Order from active intermedate first to root last
    cert_chain: chain
    tink_enc_keyset: keyset
    tink_key_resource: resource
    tink_hcvault_token: token
    kms_key_resource: resource
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: true
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 80  # must match .Values.server.svcPort
        protocol: TCP
        targetPort: 5555
      - name: metrics
        port: 2112
        protocol: TCP
        targetPort: 2112
  ingress:
    http:
      enabled: true
      className: "nginx"
      annotations: {}
      hosts:
      - path: /
        host: "timestamp.localhost"
      tls: []
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
  tolerations: []
  nodeSelector: {}
  affinity: {}

# Force namespace of namespaced resources
forceNamespace: ""
