apiVersion: v2
description: The Helm chart for Policy  Controller
home: https://github.com/sigstore/policy-controller

sources:
  - https://github.com/sigstore/policy-controller

type: application

name: policy-controller
version: 0.3.8
appVersion: 0.4.2

maintainers:
  - name: dlorenc
  - name: hectorj2f

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: policy-controller
      image: ghcr.io/sigstore/policy-controller/policy-controller:v0.4.2@sha256:435373b2bde7ed3fe133ff0d59bb4a23a0e15762320c9547fe6d1d042ab50c6c
    - name: policywebhook
      image: ghcr.io/sigstore/policy-controller/policy-webhook:v0.4.2@sha256:7ed0b012751d9941cb7b969ab2c37f5633d4dba2b2b445a6e6e23a91de554d6b
