apiVersion: v2
description: The Helm chart for Policy  Controller
home: https://github.com/sigstore/policy-controller

sources:
  - https://github.com/sigstore/policy-controller

type: application

name: policy-controller
version: 0.3.2
appVersion: 0.4.0

maintainers:
  - name: dlorenc
  - name: hectorj2f

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: policy-controller
      image: ghcr.io/sigstore/policy-controller/policy-controller:v0.4.0@sha256:2b1c017535f6a0f672ec38279f3792ca1181555342a2deae53605e202afb9764
    - name: policywebhook
      image: ghcr.io/sigstore/policy-controller/policy-webhook:v0.4.0@sha256:03f6b9807103c988439741fdc2ec4410a85c13ba62fbad58448a070ac07bb5bc
