apiVersion: v2
description: The Helm chart for Policy  Controller
home: https://github.com/sigstore/policy-controller

sources:
  - https://github.com/sigstore/policy-controller

type: application

name: policy-controller
version: 0.3.9
appVersion: 0.5.2

maintainers:
  - name: dlorenc
  - name: hectorj2f

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: policy-controller
      image: ghcr.io/sigstore/policy-controller/policy-controller:v0.5.2@sha256:f23a23910f873d01864c01122120666adf78a1dbb43f674c4d423d5fe480a718
    - name: policywebhook
      image: ghcr.io/sigstore/policy-controller/policy-webhook:v0.5.2@sha256:ae3d5b549c269c8b2a9b208d812365b6fc610d7a21c9ced8dc7eaae0a1914c09
