apiVersion: v2
description: The Helm chart for Policy  Controller
home: https://github.com/sigstore/policy-controller

sources:
  - https://github.com/sigstore/policy-controller

type: application

name: policy-controller
version: 0.9.0
appVersion: 0.12.0

maintainers:
  - name: dlorenc
  - name: hectorj2f

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: policy-controller
      image: ghcr.io/sigstore/policy-controller/policy-controller:v0.12.0@sha256:6b51f336dec9e9adff29606855dbd2c7910c5eb80d6579795a29cb3844428efc
