apiVersion: v2
name: sigstore-prober
description: Sigstore API Endpoint Prober

type: application

version: 0.1.4
appVersion: 0.7.28


keywords:
  - security
  - prober

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: sigstore-prober
      image: ghcr.io/sigstore/scaffolding/prober:v0.7.28@sha256:545d3990d399d4eb7ce0447c06284f5fe8219bcc5b38e77b2c36f866ceed225e
