apiVersion: v2
name: sigstore-prober
description: Sigstore API Endpoint Prober

type: application

version: 0.0.22
appVersion: 0.6.17


keywords:
  - security
  - prober

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: sigstore-prober
      image: ghcr.io/sigstore/scaffolding/prober:v0.6.17@sha256:b6f9b7d9debcdf9b586625dd776f082260dc263e9e104cd810470e7420b6c5e7
