apiVersion: v2
name: sigstore-prober
description: Sigstore API Endpoint Prober

type: application

version: 0.1.8
appVersion: 0.7.31


keywords:
  - security
  - prober

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: sigstore-prober
      image: ghcr.io/sigstore/scaffolding/prober:v0.7.31@sha256:b2a7d44a362211aef800214f105bd0b4f54b53de5b32818321e3167c22312666
