apiVersion: v2
name: sigstore-prober
description: Sigstore API Endpoint Prober

type: application

version: 0.2.0
appVersion: 1.0.0


keywords:
  - security
  - prober

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: sigstore-prober
      image: ghcr.io/sigstore/sigstore-probers/prober:v1.0.0@sha256:1660956b4eb249970c8c2a2ff6fb2dad78e855a6a64af87d5aa62f674784b54f
