apiVersion: v2
name: sigstore-prober
description: Sigstore API Endpoint Prober

type: application

version: 0.0.3
appVersion: 0.4.6


keywords:
  - security
  - prober

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: sigstore-prober
      image: ghcr.io/sigstore/scaffolding/prober@sha256:d16b6489228e30cccda4395086148375f2f1aff395aa0b66dc54cfd46cf6309f
