namespace:
  create: true
  name: sigstore-prober
serviceAccount:
  name: default
  create: false
  annotations: {}
spec:
  replicaCount: 1
  image: ghcr.io/sigstore/scaffolding/prober:v0.7.31@sha256:b2a7d44a362211aef800214f105bd0b4f54b53de5b32818321e3167c22312666
  imagePullPolicy: Always
  matchLabels:
    app: sigstore-prober
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  args:
    staging: false
    signingConfig: ""
    trustedRoot: ""
    rekorV2Url: ""
    rekorRequests: []
    fulcioRequests: []
    writeProber: false
    grpcPort: 5554
    disableGrpc: true
    frequency: 10
prometheus:
  port: 8080
tolerations: []
nodeSelector: {}
affinity: {}
