namespace:
  create: true
  name: sigstore-prober
serviceAccount:
  name: default
  create: false
  annotations: {}
spec:
  replicaCount: 1
  image: ghcr.io/sigstore/scaffolding/prober:v0.7.29@sha256:7bf2fcee8c1e07e5c5c7f3fe3d59cd2aa34288489f423dac67f2136ed62b6fb6
  imagePullPolicy: Always
  matchLabels:
    app: sigstore-prober
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  args:
    staging: false
    signingConfig: ""
    trustedRoot: ""
    rekorV2Url: ""
    rekorRequests: []
    fulcioRequests: []
    writeProber: false
    grpcPort: 5554
    disableGrpc: true
    frequency: 10
prometheus:
  port: 8080
tolerations: []
nodeSelector: {}
affinity: {}
