namespace:
  create: true
  name: sigstore-prober
serviceAccount:
  name: default
  create: false
  annotations: {}
spec:
  replicaCount: 1
  image: ghcr.io/sigstore/scaffolding/prober:v0.7.28@sha256:545d3990d399d4eb7ce0447c06284f5fe8219bcc5b38e77b2c36f866ceed225e
  imagePullPolicy: Always
  matchLabels:
    app: sigstore-prober
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  args:
    staging: false
    signingConfig: ""
    trustedRoot: ""
    rekorV2Url: ""
    rekorRequests: []
    fulcioRequests: []
    writeProber: false
    grpcPort: 5554
    insecure: true
    frequency: 10
prometheus:
  port: 8080
tolerations: []
nodeSelector: {}
affinity: {}
