namespace:
  create: true
  name: sigstore-prober
serviceAccount:
  name: default
  create: false
  annotations: {}
spec:
  replicaCount: 1
  image: ghcr.io/sigstore/sigstore-probers/prober:v1.0.0@sha256:1660956b4eb249970c8c2a2ff6fb2dad78e855a6a64af87d5aa62f674784b54f
  imagePullPolicy: Always
  matchLabels:
    app: sigstore-prober
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  args:
    staging: false
    signingConfig: ""
    trustedRoot: ""
    rekorV2Url: ""
    rekorRequests: []
    fulcioRequests: []
    writeProber: false
    grpcPort: 5554
    disableGrpc: true
    frequency: 10
prometheus:
  port: 8080
tolerations: []
nodeSelector: {}
affinity: {}
