namespace:
  create: true
  name: sigstore-prober
serviceAccount:
  name: default
  create: false
spec:
  replicaCount: 1
  image: ghcr.io/sigstore/scaffolding/prober:v0.6.17@sha256:b6f9b7d9debcdf9b586625dd776f082260dc263e9e104cd810470e7420b6c5e7
  imagePullPolicy: Always
  matchLabels:
    app: sigstore-prober
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  args:
    fulcioHost: https://fulcio.sigstore.dev
    rekorHost: https://rekor.sigstore.dev
    frequency: 10
    writeProber: false
    rekorRequests: []
    fulcioRequests: []
    trustRekorAPIPublicKey: false
prometheus:
  port: 8080
