{{- if .Values.createcerts.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fulcio.createcerts.fullname" . }}
{{ include "fulcio.namespace" . | indent 2 }}
  labels:
    {{- include "fulcio.labels" . | nindent 4 }}
{{- if .Values.createcerts.annotations }}
  annotations:
{{ toYaml .Values.createcerts.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.createcerts.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.createcerts.ttlSecondsAfterFinished }}
{{- end }}
  template:
    spec:
      serviceAccountName: {{ template "fulcio.serviceAccountName.createcerts" . }}
      restartPolicy: Never
      automountServiceAccountToken: {{ .Values.createcerts.serviceAccount.mountToken }}
      containers:
        - name: {{ template "fulcio.createcerts.fullname" . }}
          image: "{{ template "fulcio.image" .Values.createcerts.image }}"
          imagePullPolicy: "{{ .Values.createcerts.image.pullPolicy }}"
          args: ["--secret={{ .Values.server.secret }}"]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
    {{- if .Values.createcerts.securityContext }}
      securityContext:
{{ toYaml .Values.createcerts.securityContext | indent 8 }}
    {{- end }}
{{- end }}
