{{- if .Values.trillianLogServer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "rekor.mysql.labels" . | nindent 4 }}
  name: {{ template "rekor.serviceAccountName.trillianLogServer" . }}
{{ include "rekor.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.trillianLogServer.serviceAccount.annotations | indent 4 }}
{{- end }}

