apiVersion: v2
description: The Helm chart for Cosigned
home: https://github.com/sigstore/cosign

sources:
  - https://github.com/sigstore/cosign

type: application

name: cosigned
version: v0.1.10
appVersion: v1.4.1

maintainers:
  - name: dlorenc
  - name: hectorj2f

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: cosigned
      image: gcr.io/projectsigstore/cosigned:v1.4.1@sha256:d1aee97490481dae0a979913bb92fa749164fbc91a314a6b5d94aa1a87b69396
