apiVersion: v2
description: The Helm chart for Cosigned
home: https://github.com/sigstore/cosign

sources:
  - https://github.com/sigstore/cosign

type: application

name: cosigned
version: 0.1.12
appVersion: 1.5.2

maintainers:
  - name: dlorenc
  - name: hectorj2f

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: cosigned
      image: gcr.io/projectsigstore/cosigned:v1.5.2@sha256:18c7db5051c0d5ac147b1785567ef647f23f7949ae5858776561cfc9cd8cc4b2
