apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sigstore-prober.name" . }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.spec.replicaCount }}
  selector:
    matchLabels:
      {{- include "sigstore-prober.common.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sigstore-prober.common.matchLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.prometheus.port }}"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ template "sigstore-prober.name" . }}
        image: "{{ .Values.spec.image }}"
        resources:
        {{- with .Values.spec.resources }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        imagePullPolicy: "{{ .Values.spec.imagePullPolicy }}"
        args:
          {{- include "sigstore-prober.args" . | nindent 8 }}
        ports:
        - containerPort: {{ .Values.prometheus.port }} # metrics
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          allowPrivilegeEscalation: false
        env:
          # HOME set to /tmp since the default home dir for user 65534 is set to /nonexistant
        - name: HOME
          value: "/tmp"
        {{- if or .Values.spec.args.signingConfig .Values.spec.args.trustedRoot }}
        volumeMounts:
        - name: sigstore-config
          mountPath: "/var/run/sigstore"
          readOnly: true
        {{- end }}
      {{- if or .Values.spec.args.signingConfig .Values.spec.args.trustedRoot }}
      volumes:
        - name: sigstore-config
          configMap:
            name: {{ template "sigstore-prober.name" . }}-config
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
