apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sigstore-prober.name" . }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.spec.replicaCount }}
  selector:
    matchLabels:
      {{- include "sigstore-prober.common.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sigstore-prober.common.matchLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.prometheus.port }}"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.spec.args.trustRekorAPIPublicKey }}
      initContainers:
      - name: public-key-fetcher
        image: docker.io/curlimages/curl@sha256:9fab1b73f45e06df9506d947616062d7e8319009257d3a05d970b0de80a41ec5
        args:
          - "--output"
          - "/var/run/sigstore/public-key.pem"
          - "{{ .Values.spec.args.rekorHost }}/api/v1/log/publicKey"
        env:
        volumeMounts:
        - name: sigstore
          mountPath: "/var/run/sigstore"
      {{- end }}
      containers:
      - name: {{ template "sigstore-prober.name" . }}
        image: "{{ .Values.spec.image }}"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        imagePullPolicy: "{{ .Values.spec.imagePullPolicy }}"
        args:
          {{- include "sigstore-prober.args" . | nindent 8 }}
        ports:
        - containerPort: {{ .Values.prometheus.port }} # metrics
      {{- if .Values.spec.args.trustRekorAPIPublicKey }}
        env:
        - name: SIGSTORE_REKOR_PUBLIC_KEY
          value: "/var/run/sigstore/public-key.pem"
        volumeMounts:
        - name: sigstore
          mountPath: "/var/run/sigstore"
          readOnly: true
      volumes:
        - name: sigstore
          emptyDir: {}
      {{- end }}
