apiVersion: batch/v1
kind: Job
metadata:
  labels:
    {{- include "rekor.server.labels" . | nindent 4 }}
  name: {{ template "rekor.createtree.fullname" . }}
{{- if .Values.createtree.annotations }}
  annotations:
{{ toYaml .Values.createtree.annotations | indent 4 }}
{{- end }}
{{ include "rekor.namespace" . | indent 2 }}
spec:
{{- if .Values.createtree.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.createtree.ttlSecondsAfterFinished }}
{{- end }}
  template:
    spec:
      serviceAccountName: {{ template "rekor.serviceAccountName.createtree" . }}
      restartPolicy: Never
      automountServiceAccountToken: true
      containers:
        - name: {{ template "rekor.createtree.fullname" . }}
          image: "{{ template "rekor.image" .Values.createtree.image }}"
          args: ["--namespace=$(NAMESPACE)",
            "--configmap={{ template "rekor.config" . }}",
            "--display_name=rekortree",
            {{- if .Values.trillian.adminServer }}
            "--admin_server={{ .Values.trillian.adminServer }}",
            {{- else }}
            "--admin_server={{ .Values.trillian.logServer.name }}.{{ .Values.trillian.forceNamespace }}:{{ .Values.trillian.logServer.portRPC}}",
            {{- end }}
            "--force={{ .Values.createtree.force }}"
          ]
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
{{ toYaml .Values.createtree.resources | indent 12 }}
    {{- if .Values.createtree.securityContext }}
      securityContext:
{{ toYaml .Values.createtree.securityContext | indent 8 }}
    {{- end }}
