{{- if .Values.server.ingress.enabled }}
apiVersion: "networking.k8s.io/v1"
kind: Ingress
metadata:
  labels:
    {{- include "rekor.server.labels" . | nindent 4 }}
  name: {{ template "rekor.server.fullname" . }}
{{ include "rekor.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.server.ingress.annotations | indent 4 }}
spec:
{{- if .Values.server.ingress.className }}
  ingressClassName: {{ .Values.server.ingress.className }}
{{- end }}
  rules:
    {{- range .Values.server.ingress.hosts }}
    - host: {{ required "An Ingress hostname is required" .host | quote }}
      http:
        paths:
          - path: {{ .path }}
            pathType: {{ default "Prefix" .pathType }}
            backend: {{- include "rekor.server.ingress.backend" $  | nindent 14 }}
    {{- end }}
{{- if .Values.server.ingress.tls }}
  tls:
    {{- range .Values.server.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
{{- end }}
{{- end -}}
{{- range .Values.server.ingresses }}
{{- if .enabled }}
---
apiVersion: "networking.k8s.io/v1"
kind: Ingress
metadata:
  labels:
    {{- include "rekor.server.labels" $ | nindent 4 }}
  name: {{ include "rekor.server.fullname" $ }}-{{ .name }}
{{ include "rekor.namespace" $ | indent 2 }}
  annotations:
{{- if eq .className "gce"}}
    kubernetes.io/ingress.class: "gce"
    {{- if .frontendConfigSpec }}
    networking.gke.io/v1beta1.FrontendConfig: "{{ include "rekor.server.fullname" $ }}-{{ .name }}"
    {{- end }}
    {{- if .staticGlobalIP }}
    kubernetes.io/ingress.global-static-ip-name: {{ .staticGlobalIP | quote }}
    {{- end }}
{{- end }}
{{- with .annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if and (.className) (not (eq .className "gce")) }}
  ingressClassName: {{ .className }}
{{- end }}
  rules:
    {{- range .hosts }}
    - host: {{ required "An Ingress hostname is required" .host | quote }}
      http:
        paths:
          - path: {{ .path }}
            pathType: {{ default "Prefix" .pathType }}
            backend: {{- include "rekor.server.ingress.backend" $  | nindent 14 }}
    {{- end }}
{{- if .tls }}
  tls:
    {{- range .tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
