{{- if .Values.server.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "rekor.server.labels" . | nindent 4 }}
  name: {{ template "rekor.serviceAccountName.server" . }}
{{ include "rekor.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.server.serviceAccount.annotations | indent 4 }}
{{- end }}

