name: Test Charts

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0

      - name: Get changed files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            charts:
              - 'charts/**'

      - name: Set up Helm
        if: steps.changes.outputs.charts == 'true'
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        if: steps.changes.outputs.charts == 'true'
        with:
          python-version: '3.13'
          check-latest: true

      - name: Set up chart-testing
        if: steps.changes.outputs.charts == 'true'
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0

      - name: Run chart-testing (lint)
        if: steps.changes.outputs.charts == 'true'
        run: ct lint --config ct.yaml

      - name: "Add NGINX Ingress Repository"
        if: steps.changes.outputs.charts == 'true'
        run: |
          helm repo add ingress-nginx "https://kubernetes.github.io/ingress-nginx"
          helm repo update

      - name: Create KIND Cluster
        if: steps.changes.outputs.charts == 'true'
        uses: helm/kind-action@92086f6be054225fa813e0a4b13787fc9088faab # v1.13.0

      - name: Install Ingress Controller
        if: steps.changes.outputs.charts == 'true'
        run: "helm install ingress-nginx/ingress-nginx --generate-name --set controller.service.type='NodePort' --set controller.admissionWebhooks.enabled=false --set controller.progressDeadlineSeconds=30"

      - name: Run chart-testing (install)
        if: steps.changes.outputs.charts == 'true'
        run: ct install --config ct-install.yaml
